"""
Constants for the IMC Prosperity Round 1 trading system.
"""

PRODUCTS = ["ASH_COATED_OSMIUM", "INTARIAN_PEPPER_ROOT"]

POSITION_LIMITS = {
    "ASH_COATED_OSMIUM": 50,
    "INTARIAN_PEPPER_ROOT": 50,
}

TIMESTAMP_STEP = 100
TIMESTAMPS_PER_DAY = 10000
MAX_TIMESTAMP = 999900

DATA_DIR = "c:/IMC/ROUND1"
OUTPUT_DIR = "c:/IMC/ROUND1/output"

DAYS = [-2, -1, 0]
